### ISSUE TITLE
Build and publish examples

### ISSUE THREAD

**Issue by adrigzr** [BBVAEngineering/ember-cli-polymer#2]
Add task to build and publish examples github page to travis release step.

**Comment by kcmr** [comment]
Why not to use the travis pages provider? 

Something like this:
```
script: npm run build -- -prod

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  verbose: true
  on:
    branch: master
```
